name: juan_kite
description: Juan's take on the Kagi's Kite.
version: 1.0.2+2
publish_to: none

environment:
  sdk: ^3.5.0
  flutter: ">=3.29.3"

dependencies:
  beamer: ^1.7.0
  bloc: ^9.0.0
  cached_network_image: ^3.4.1
  dio: ^5.8.0+1
  equatable: ^2.0.7
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  flutter_localizations:
    sdk: flutter
  intl: ^0.19.0
  json_annotation: ^4.9.0
  url_launcher: ^6.3.1

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.15
  flutter_test:
    sdk: flutter
  http_mock_adapter: ^0.6.1
  json_serializable: ^6.9.5
  mocktail: ^1.0.4
  very_good_analysis: ^7.0.0

flutter:
  uses-material-design: true
  generate: true
