name: juan_kite

concurrency:
  group: $-$
  cancel-in-progress: true

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  semantic-pull-request:
    permissions:
      pull-requests: write
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/semantic_pull_request.yml@v1

  # https://workflows.vgv.dev/docs/workflows/flutter_package
  build:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/flutter_package.yml@v1
    with:
      flutter_channel: stable
      flutter_version: 3.29.3
      test_recursion: true
      coverage_excludes: "**/*.g.dart lib/l10n/arb/*.dart"
      min_coverage: 75
      format_directories: $(find . -name '*.dart' -not -name '*.g.dart' -not -name '*.gen.dart' -not -name '*.mocks.dart' -not -name '*.freezed.dart' -not -name '*.graphql.dart' -not -path './lib/l10n/arb/*' -not -path '**/.dart_tool/*')

  spell-check:
    uses: VeryGoodOpenSource/very_good_workflows/.github/workflows/spell_check.yml@v1
    with:
      includes: |
        **/*.md
      modified_files_only: false
